#!/usr/bin/env php
<?php
require __DIR__.'/bootstrap.php';
use App\Utils\Console;

$f3 = \Base::instance();

$f3->set('BASE_DIR', __DIR__);

$f3->set('DB', $db);

$f3->config($f3->get('BASE_DIR').'/config/app.ini', true);

$f3->route('GET / [cli]', function($f3){
    Console::log($f3->get('APP'), 'green');
});

$f3->run();